# Configuration for Kubernetes cluster
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  selector:
    app: authentication-service
    # says that IP address assigned to this service will be accessible in our cluster
    type: ClusterIP
    ports:
      - port: 3010
        targetPort: 3010
        protocol: TCP
