export const {
  PORT,
  MODULE_NAME,
  AUTH_SERVICE_DATABASE_HOST,
  AUTH_SERVICE_DATABASE,
  AUTH_SERVICE_DATABASE_PORT,
  AUTH_SERVICE_DATABASE_USERNAME,
  AUTH_SERVICE_DATABASE_PASSWORD,
  JWT_SECRET,
} = process.env;
